language: node_js

node_js:
  - 5.9
  - 5

sudo: required

env:
  - GREMLINSERVER_VERSION="3.1.1"

install:
  # install Oracle JDK8
  - sh -c ./build/jdk8-install.sh
  # install gremlin-server
  - sh -c ./build/gremlin-server/install.sh
  # install dependencies
  - npm install

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
  - npm run build

script: npm run test:node && npm run test:browser:coverage
